'use client'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, ChevronDown, Menu, X, MessageCircle, Sun, CheckCircle2, Home, Building2, Factory, Zap, Phone, MapPin } from 'lucide-react'
import { company, navLinks } from '@/lib/site-data'

export function Icon({ name, size = 24 }: { name: string; size?: number }) { const props = { size, strokeWidth: 1.8 }; if (name === 'home') return <Home {...props}/>; if (name === 'building') return <Building2 {...props}/>; if (name === 'factory') return <Factory {...props}/>; return <Sun {...props}/> }
export function Navbar() { const [open, setOpen] = useState(false); return <header className="absolute inset-x-0 top-0 z-50"><div className="container-site flex h-24 items-center justify-between border-b border-white/10"><Link href="/" className="focus-ring flex items-center gap-2 text-white"><span className="grid size-9 place-items-center rounded-xl bg-accent text-accent-foreground"><Sun size={21} fill="currentColor"/></span><span className="font-display text-lg font-semibold tracking-tight">surya<span className="text-accent">urja</span></span></Link><nav className="hidden items-center gap-7 md:flex">{navLinks.map((link)=><Link key={link.href} href={link.href} className="focus-ring text-sm text-white/75 transition hover:text-white">{link.label}</Link>)}<Link href="/contact" className="btn-primary text-sm">Get a free quote <ArrowRight size={16}/></Link></nav><button aria-label={open ? 'Close menu' : 'Open menu'} onClick={()=>setOpen(!open)} className="focus-ring rounded-lg p-2 text-white md:hidden">{open?<X/>:<Menu/>}</button></div>{open&&<div className="container-site pb-4 md:hidden"><nav className="grid gap-1 rounded-2xl bg-primary p-3 shadow-xl">{navLinks.map((link)=><Link onClick={()=>setOpen(false)} key={link.href} href={link.href} className="rounded-xl p-3 text-sm text-white hover:bg-white/10">{link.label}</Link>)}<Link onClick={()=>setOpen(false)} href="/contact" className="btn-primary mt-2">Get a free quote <ArrowRight size={16}/></Link></nav></div>}</header> }
export function WhatsAppButton() { return <a aria-label="Chat with Surya Urja on WhatsApp" href={`https://wa.me/${company.whatsapp}?text=${encodeURIComponent('Hello, I am interested in installing solar at my property in Nagpur. I would like a free consultation.')}`} target="_blank" rel="noreferrer" className="focus-ring fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full bg-[#1e8e55] px-4 py-3 text-sm font-semibold text-white shadow-lg transition hover:-translate-y-1"><MessageCircle size={19}/> WhatsApp us</a> }
export function Footer() { return <footer className="bg-[#0d2d21] py-14 text-white"><div className="container-site grid gap-12 md:grid-cols-[1.4fr_1fr_1fr]"><div><div className="mb-4 flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-accent text-accent-foreground"><Sun size={20} fill="currentColor"/></span><span className="font-display text-lg font-semibold">surya<span className="text-accent">urja</span></span></div><p className="max-w-sm text-sm leading-6 text-white/60">Thoughtful solar systems for the homes, businesses and industries powering Maharashtra forward.</p></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-accent">Explore</p><div className="grid gap-3 text-sm text-white/65"><Link href="/about" className="hover:text-white">About us</Link><Link href="/solutions/residential" className="hover:text-white">Residential solar</Link><Link href="/solutions/commercial" className="hover:text-white">Commercial solar</Link><Link href="/solutions/industrial" className="hover:text-white">Industrial solar</Link><Link href="/projects" className="hover:text-white">Our projects</Link><Link href="/solar-calculator" className="hover:text-white">Solar calculator</Link><Link href="/blog" className="hover:text-white">Insights</Link></div></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-accent">Connect</p><div className="grid gap-3 text-sm text-white/65"><a href={`tel:${company.phone}`} className="flex items-center gap-2 hover:text-white"><Phone size={15}/> {company.phone}</a><a href={`mailto:${company.email}`} className="hover:text-white">{company.email}</a><span className="flex items-center gap-2"><MapPin size={15}/> {company.city}</span></div></div></div><div className="container-site mt-12 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-white/40 md:flex-row"><span>© 2026 Surya Urja. Built for a brighter Maharashtra.</span><div className="flex gap-4"><Link href="/privacy-policy">Privacy</Link><Link href="/terms-and-conditions">Terms</Link></div></div></footer> }
export function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-primary"><span className="h-px w-8 bg-accent"/>{children}</p> }
export function FAQ() { const [active, setActive] = useState(0); const { faqs } = require('@/lib/site-data') as typeof import('@/lib/site-data'); return <div className="grid gap-3">{faqs.map((faq, i)=><div key={faq.q} className="border-b border-border"><button className="focus-ring flex w-full items-center justify-between gap-4 py-5 text-left font-display text-sm font-semibold" onClick={()=>setActive(active===i?-1:i)} aria-expanded={active===i}>{faq.q}<ChevronDown className={`shrink-0 transition ${active===i?'rotate-180':''}`} size={18}/></button>{active===i&&<p className="max-w-2xl pb-5 text-sm leading-6 text-muted-foreground">{faq.a}</p>}</div>)}</div> }
export { ArrowRight, CheckCircle2, Zap }
